---
title: Auro Data Structure
---
erDiagram
    FIAT {
        int id PK "AUTOINCREMENT"
        text name "NOT NULL"
        text symbol "NOT NULL" 
        timestamp created_at "DEFAULT CURRENT_TIMESTAMP"
        timestamp updated_at "DEFAULT CURRENT_TIMESTAMP"
    }
    FIAT_RAMP{
        text id PK
        int fiat_id FK "NOT NULL references fiat(id)"
        real fiat_amount "NOT NULL"
        date ramp_date "NOT NULL DEFAULT CURRENT_DATE"
        varchar(255) via_exchange "NOT NULL"
        varchar(8) kind " NOT NULL CHECK (kind IN ('deposit', 'withdraw')) " 
        timestamp created_at "DEFAULT CURRENT_TIMESTAMP"
        timestamp updated_at "DEFAULT CURRENT_TIMESTAMP"
    }

    FIAT ||--o{ FIAT_RAMP : ramp

    SYS_TRACKER {
        int id PK "AUTOINCREMENT"
        text name "NOT NULL"
        timestamp last_updated_at "DEFAULT CURRENT_TIMESTAMP"
    }

    FIAT_RATE{
        int id PK "AUTOINCREMENT"
        int base_fiat_id FK "NOT NULL references fiat(id)"
        date date "NOT NULL"
        text rates "NOT NULL JSON_TEXT({symbol::text: rate::real})"
        timestamp created_at "DEFAULT CURRENT_TIMESTAMP"
        timestamp updated_at "DEFAULT CURRENT_TIMESTAMP"
    }

    
    
